import { useMemo, useState } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import topics from "../data/topics.json";
import quizBank from "../data/quiz-bank.json";
import extraQuestions from "../data/quiz-duel-extra.json";
import { recordQuizDuelRun } from "../lib/storage.js";

const N=15;
const corrections={
 q112:{options:["studieuse","studieux","studieuses","travailleur"],correctIndex:1,explanation:"Studieux is masculine plural here."},
 q124:{options:["riiez","riez","avez ri","rirez"],correctIndex:0,explanation:"The imparfait of rire for vous is riiez."},
 q136:{options:["au","en","à","aux"],correctIndex:0,explanation:"Ghana is masculine singular: au Ghana."}
};
const bank=()=>[...quizBank,...extraQuestions].map(q=>corrections[q.id]?{...q,...corrections[q.id]}:q);
const shuffle=a=>[...a].sort(()=>Math.random()-.5);const enc=ids=>ids.map(id=>id.replace(/^q/,"")).join("-");const dec=s=>s.split("-").map(id=>`q${String(Number(id)).padStart(3,"0")}`);
function makeSession(topicId,ids){const all=bank();const pool=ids?.length?ids.map(id=>all.find(q=>q.id===id)).filter(Boolean):shuffle(topicId?all.filter(q=>q.topicId===topicId):all).slice(0,N);return pool.map(q=>({...q,shuffledOptions:shuffle(q.options.map((text,i)=>({text,correct:i===q.correctIndex})))}));}

export default function QuizDuel(){
 const {topicId}=useParams();const [params]=useSearchParams();const topic=topics.find(t=>t.id===topicId);const incoming=params.get("c");const inviteName=params.get("nm")||"a friend";const incomingIds=useMemo(()=>incoming?dec(incoming):null,[incoming]);
 const [phase,setPhase]=useState("intro"),[session,setSession]=useState([]),[qi,setQi]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[english,setEnglish]=useState(false),[name,setName]=useState(()=>localStorage.getItem("french_duel_name")||"Player"),[link,setLink]=useState(""),[copied,setCopied]=useState(false),[started,setStarted]=useState(0),[elapsed,setElapsed]=useState(0);const q=session[qi];
 const start=(ids=null)=>{const s=makeSession(topicId,ids);if(!s.length)return;setSession(s);setQi(0);setSelected(null);setScore(0);setEnglish(false);setStarted(Date.now());setElapsed(0);setPhase("playing");localStorage.setItem("french_duel_name",name.trim().slice(0,20)||"Player");};
 const create=()=>{const s=makeSession(topicId);setSession(s);const base=topicId?`/duel/${topicId}`:"/duel";const u=`${location.origin}${location.pathname}#${base}?c=${enc(s.map(q=>q.id))}&nm=${encodeURIComponent(name||"Player")}`;setLink(u);setPhase("share");localStorage.setItem("french_duel_session",JSON.stringify({ids:s.map(q=>q.id),topicId,name,createdAt:Date.now()}));};
 const share=async()=>{const text=`Join my French Quiz Duel session. Take the same questions and check your corrections: ${link}`;window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer");try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1800);}catch{}};
 const pick=o=>{if(selected)return;setSelected(o);setScore(s=>s+(o.correct?1:0));setElapsed(Math.floor((Date.now()-started)/1000));};
 const next=()=>{if(qi+1<session.length){setQi(i=>i+1);setSelected(null);setEnglish(false);return;}const t=Math.floor((Date.now()-started)/1000);recordQuizDuelRun({topicId:topicId||"all",score,total:session.length,timeSec:t,streak:0});setElapsed(t);setPhase("results");};
 if(phase==="intro")return <div className="max-w-xl mx-auto space-y-5"><div className="text-center"><div className="text-3xl mb-3">⚔️</div><p className="text-xs text-white/40 uppercase tracking-wider">Shared quiz session</p><h1 className="font-display text-2xl font-bold">Quiz Duel {topic?`— ${topic.title}`:"— All Topics"}</h1><p className="text-sm text-white/50 mt-2">Create one quiz, share the link on WhatsApp, and let friends take the exact same questions.</p></div><div className="glass rounded-2xl p-5 space-y-3"><label className="text-xs text-white/45">Your name</label><input value={name} onChange={e=>setName(e.target.value)} className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3" placeholder="Your name"/><button onClick={()=>start(incomingIds)} className="w-full py-3 rounded-xl bg-amber-400 text-black font-bold">{incoming?`Take ${inviteName}'s session`:"Start quiz"}</button><button onClick={create} className="w-full py-3 rounded-xl bg-white/10 font-medium">Create & share quiz session</button></div>{incoming&&<p className="text-xs text-white/45 text-center">The link carries the question set. Your answers, score and corrections remain on your device.</p>}</div>;
 if(phase==="share")return <div className="max-w-lg mx-auto text-center"><div className="glass rounded-2xl p-6"><p className="text-xs text-white/40 uppercase tracking-wider">Session ready</p><h1 className="font-display text-2xl font-bold mt-2">Share this quiz</h1><p className="text-sm text-white/50 mt-2">Everyone gets the same {session.length} questions and their own corrections.</p><div className="mt-5 bg-white/5 border border-white/10 rounded-xl p-3 text-left text-xs break-all text-white/60">{link}</div><button onClick={share} className="mt-4 w-full py-3 rounded-xl bg-[#25D366] text-white font-bold">{copied?"Link copied":"Share on WhatsApp"}</button><button onClick={()=>start(session.map(q=>q.id))} className="mt-2 w-full py-3 rounded-xl bg-white/10">Take this session myself</button></div></div>;
 if(phase==="playing"&&q)return <div className="max-w-xl mx-auto space-y-4"><div className="flex justify-between text-xs font-mono text-white/50"><span>Q{qi+1}/{session.length}</span><span>Score {score}</span><span>{elapsed}s</span></div><div className="glass rounded-2xl p-6"><p className="font-display text-xl font-semibold leading-snug">{q.prompt}</p>{q.promptEn&&<><button onClick={()=>setEnglish(v=>!v)} className="mt-3 text-xs px-3 py-1.5 rounded-full bg-white/10">{english?"Hide English":"Show English"}</button>{english&&<div className="mt-3 p-3 rounded-xl border border-white/10 bg-white/5 text-sm text-white/70"><span className="block text-[10px] uppercase text-white/35 mb-1">English</span>{q.promptEn}</div>}</>}<div className="space-y-2 mt-5">{q.shuffledOptions.map((o,i)=>{const chosen=selected===o;const cls=selected?(o.correct?"bg-emerald-500/15 border-emerald-400/30":chosen?"bg-rose-500/15 border-rose-400/30":"bg-white/5 border-white/10"):"bg-white/5 border-white/10 hover:bg-white/10";return <button key={i} disabled={!!selected} onClick={()=>pick(o)} className={`w-full text-left px-4 py-3 rounded-xl border text-sm ${cls}`}><span className="font-mono text-white/35 mr-2">{String.fromCharCode(65+i)}.</span>{o.text}</button>})}</div>{selected&&<div className="mt-4 border-t border-white/10 pt-4"><p className={selected.correct?"text-emerald-300":"text-rose-300"}>{selected.correct?"✓ Correct":"✗ Not quite"}</p><p className="text-sm text-white/55 mt-1">{q.explanation}</p><button onClick={next} className="mt-3 px-4 py-2 rounded-xl bg-white/10 text-sm">{qi+1===session.length?"See results":"Next question"}</button></div>}</div></div>;
 const accuracy=session.length?Math.round(score/session.length*100):0;return <div className="max-w-lg mx-auto space-y-5 text-center"><div className="glass rounded-2xl p-7"><p className="text-xs text-white/40 uppercase tracking-wider">Session complete</p><h1 className="font-display text-3xl font-bold mt-2">{score}/{session.length}</h1><p className="text-white/55 mt-1">{accuracy}% accuracy · {elapsed}s</p><p className="text-sm text-white/45 mt-4">Each answer was corrected immediately. Your progress is saved locally.</p></div><div className="grid grid-cols-2 gap-3"><button onClick={()=>start(session.map(q=>q.id))} className="py-3 rounded-xl bg-amber-400 text-black font-bold">Try again</button><button onClick={()=>setPhase("intro")} className="py-3 rounded-xl bg-white/10">New session</button></div><Link to="/topics" className="text-xs text-white/40">Back to topics</Link></div>;
}
